version: '3.3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: VeryStrongPassword123
    ports:
      - "1433:1433"
networks:
  backend:
