version: '3.3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: VeryStrongPassword!
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
networks:
  backend:
